name: backend-ci

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: install pipenv tool
      run: |
        pip install pipenv 
        pip install flake8
    - name: pipenv install
      run: cd starter/backend && pipenv install
    - name: run test 
      run: cd starter/backend && pipenv run lint


  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: install pipenv tool
      run: pip install pipenv
    - name: pipenv install
      run: cd starter/backend && pipenv install
    - name: run test 
      run: cd starter/backend && pipenv run test        


  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - name: Checkout
      uses: actions/checkout@v3 
    - name: install pipenv tool
      run: pip install pipenv
    - name: Build Docker image
      run: |
        cd starter/backend && docker build -t my-backend-app:${{ github.sha }} .
        echo "Build image successfully"
